apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tct0ifpfc-dotnet-basic
  janus-idp.io/tekton: tct0ifpfc-dotnet-basic
  backstage.io/kubernetes-id: tct0ifpfc-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tct0ifpfc-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
